name: ChestSQL
main: com.mengcraft.chestsql.Main
version: 0.2.2
commands:
    chest:
        description:
        usage: 
        permission: chestsql.use
        permission-message: You don't have permission
permissions:
    chestsql.use:
        description: 
        default: true