name: ChestSQL
main: com.mengcraft.ChestSQL.ChestSQL
version: 0.4.5
commands:
    chest:
        description:
        usage: 
        permission: chestsql.use
        permission-message:
    chestadmin:
        description:
        usage: 
        permission: chestsql.admin
        permission-message:
permissions:
    chestsql.use:
        description:
        default: true
    chestsql.use.vip:
        description:
        default: op
    chestsql.public.*:
        description:
        default: op
    chestsql.admin:
        description: 
        default: op
